version: '3.8'
services:
  api:
    container_name: server
    build: ./server
    image: server:1.0.0
    ports:
      - '8080:8080'
    volumes:
      - ./server:/app
      - /app/node_modules
  web:
    container_name: client
    build: ./client
    image: client:1.0.0
    ports:
      - '5173:5173'
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - api
